# Generated by Django 6.0.4 on 2026-05-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0004_alter_category_options_alter_video_category'),
        ('Demo', '0004_plan'),
    ]

    operations = [
    ]
